database:
  securityContext:
    enabled: true
    fsGroup: 1000940000
    runAsUser: 1000940000
  postgresqlUsername: cat
  postgresqlPassword: cat
  postgresqlDatabase: cat

server:
  replicaCount: 1
  image:
    repository: balcodecampcat/cat-server
    tag: 9285770a5adbe66d38d8ddd406eecab2b2b8bd92
  network:
    http:
      servicePort: 8080
      ingress:
        host: cat-server.apps.baloise.dev
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  - name: DATABASE_URL
    value: jdbc:postgresql://codes-and-texts-database:5432
  - name: DATABASE_USER
    value: cat
  - name: DATABASE_PASS
    value: cat

#frontent-angular:
#  replicaCount: 0
#  image:
#    repository: balcodecampcat/cat-frontend-angular
#    tag: latest
#  network:
#    http:
#      servicePort: 8080
#      ingress:
#        host: cat-angular.apps.baloise.dev
#  env:
#    - name: CAT_API_URL
#      value: http://cat-server.apps.baloise.dev
#
#frontent-vaadin:
#  replicaCount: 0
#  image:
#    repository: balcodecampcat/cat-frontend-vaadin
#    tag: latest
#  network:
#    http:
#      servicePort: 8080
#      ingress:
#        host: cat-vaadin.apps.baloise.dev
#  env:
#    - name: CAT_API_URL
#      value: http://cat-server.apps.baloise.dev

