database:
  replicaCount: 0
  image:
    repository: postgres
    tag: 13-alpine
  network:
    http:
      servicePort: 8080
      ingress:
        host: cat-server.apps.baloise.dev
    env:
    - name: POSTGRES_DB
      value: tbd
    - name: DATABASE_USER
      value: tbd
    - name: POSTGRES_PASSWORD
      value: tbd

server:
  replicaCount: 0
  image:
    repository: balcodecampcat/cat-server
    tag: latest
  network:
    http:
      servicePort: 8080
      ingress:
        host: cat-server.apps.baloise.dev
    env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: DATABASE_URL
      value: tbd
    - name: DATABASE_USER
      value: tbd
    - name: DATABASE_PASS
      value: tbd

frontent-angular:
  replicaCount: 0
  image:
    repository: balcodecampcat/cat-frontend-angular
    tag: latest
  network:
    http:
      servicePort: 8080
      ingress:
        host: cat-angular.apps.baloise.dev
  env:
    - name: CAT_API_URL
      value: http://cat-server.apps.baloise.dev

frontent-vaadin:
  replicaCount: 0
  image:
    repository: balcodecampcat/cat-frontend-vaadin
    tag: latest
  network:
    http:
      servicePort: 8080
      ingress:
        host: cat-vaadin.apps.baloise.dev
  env:
    - name: CAT_API_URL
      value: http://cat-server.apps.baloise.dev

