database:
  securityContext:
    enabled: true
    fsGroup: 1000940000
    runAsUser: 1000940000
  postgresqlUsername: cat
  postgresqlPassword: cat
  postgresqlDatabase: cat

catserver:
  replicaCount: 1
  image:
    repository: balcodecampcat/cat-server
    tag: 60d0200b4228f6a44e2b5b043fbcb52396fd940b
  network:
    http:
      servicePort: 8080
      ingress:
        host: cat-server.apps.baloise.dev
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: docker
  - name: DATABASE_URL
    value: jdbc:postgresql://codes-and-texts-database:5432
  - name: DATABASE_USERNAME
    value: cat
  - name: DATABASE_PASSWORD
    value: cat

frontend-vaadin:
  replicaCount: 1
  image:
    repository: balcodecampcat/cat-frontend-vaadin
    tag: 60d0200b4228f6a44e2b5b043fbcb52396fd940b
  network:
    http:
      servicePort: 8080
      ingress:
        host: cat-vaadin.apps.baloise.dev
  env:
  - name: CAT_BACKEND_URL
    value: http://catserver:8080

#frontend-angular:
#  replicaCount: 0
#  image:
#    repository: balcodecampcat/cat-frontend-angular
#    tag: latest
#  network:
#    http:
#      servicePort: 8080
#      ingress:
#        host: cat-angular.apps.baloise.dev
#  env:
#    - name: CAT_API_URL
#      value: http://cat-server.apps.baloise.dev
#
